FROM node:lts

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copia código e schema
COPY . .

# Copia script wait-for-it
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

RUN npx prisma generate

EXPOSE 3001

# Espera o MySQL estar pronto antes de aplicar migrations
CMD sh -c "/wait-for-it.sh db:3306 -- npx prisma migrate deploy && npm run start:dev"
